# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Portfolio
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This website is an example on how to use my gallery blog post to add a
  photo gallery to your blog/website.
baseurl: "/Portfolio" # the subpath of your site, e.g. /blog
url: "//KochkinaY.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: "portfolio"
    values:
      permalink: /:path/:basename:output_ext

exclude: [LICENSE-CODE.md, LICENSE-IMAGES, README.md, bower.json]
